.\" A sample man page. 
.\" Contact admin@yourcompany.com to correct errors or omissions. 
.TH autojump 1 "10 February 2009" "1.0" "A faster way to navigate your filesystem"
.SH NAME
autojump \- a faster way to navigate your filesystem
.SH SYNOPSIS
.\" Syntax goes here. 
.B j 
dirspec
.P
.B jumpstat
.SH DESCRIPTION
One of the most used shell commands is "cd". A quick survey among my friends revealed that between 10 and 20% of all commands they type are actually cd commands! Unfortunately, jumping from one part of your system to another with cd requires to enter almost the full path, which isn't very practical and requires a lot of keystrokes.
.P
.B autojump
is a faster way to navigate your filesystem. It works by maintaining a database of the directories you use the most from the command line. The 
.B jumpstat
command shows you the current contents of the database. You need to work a little bit before the database becomes useable. Once your database is reasonably complete, you can "jump" to a directory by typing:
.P
.B j
dirspec
.P
where dirspec is a few characters of the directory you want to jump to. It will jump to the most used directory whose name matches the pattern given in dirspec.
.P
Autojump supports autocompletion. Try it!
.SH EXAMPLES
.B j
mp3
.P
could jump to "/home/gwb/my\ mp3\ collection", if that is the directory in which you keep your mp3s.
.P
.B jumpstat
.P
will print out something in the lines of:
.P
54.5:	/home/shared/musique
.P
60.0:	/home/joel/workspace/coolstuff/glandu
.P
83.0:	/home/joel/workspace/abs_user/autojump
.P
97.9:	/home/joel/workspace/autojump
.P
141.8:	/home/joel/workspace/vv
.P
161.7:	/home/joel
.P
Total key weight: 1079
.P
The "key weight" reflects the amount of time you spend in a directory.
.SH BUGS
No known bugs at this time. 
.SH AUTHOR
.nf
Joel Schaerer (joel.schaerer@laposte.net)
.fi
.SH LICENSE
.B autojump
is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

autojump is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with autojump.  If not, see <http://www.gnu.org/licenses/>.

