.TH autojump 1 "10 April 2012" "release-v20"
.SS NAME
.PP
autojump - a faster way to navigate your filesystem
.SS SYNOPSIS
.PP
Jump to a previously visited directory \[aq]foobar\[aq]:
.IP
.nf
\f[C]
j\ foo
\f[]
.fi
.PP
Show all database entries and their respective key weights:
.IP
.nf
\f[C]
j\ --stat
\f[]
.fi
.SS DESCRIPTION
.PP
autojump is a faster way to navigate your filesystem.
It works by maintaining a database of the directories you use the most
from the command line.
The \f[C]j\ --stat\f[] command shows you the current contents of the
database.
Directories must be visited first before they can be jumped to.
.SS OPTIONS
.PP
Options must be passed to \[aq]autojump\[aq] and not the \[aq]j\[aq]
wrapper function.
.IP
.nf
\f[C]
-a,\ --add\ DIR\ \ \ \ \ \ \ manually\ add\ path\ to\ database

--purge\ \ \ \ \ \ \ \ \ \ \ \ \ deletes\ database\ entries\ that\ no\ longer\ exist\ on\ system

-s,\ --stat\ \ \ \ \ \ \ \ \ \ \ \ \ \ show\ database\ entries\ and\ their\ key\ weights

--version\ \ \ \ \ \ \ \ \ \ \ show\ version\ information\ and\ exit
\f[]
.fi
.SS INTERNAL OPTIONS
.IP
.nf
\f[C]
-b,\ --bash\ \ \ \ \ \ \ \ \ \ enclose\ directory\ with\ quotes\ to\ prevent\ errors

--complete\ \ \ \ \ \ \ \ \ \ used\ for\ tab\ completion
\f[]
.fi
.SS ADDITIONAL CONFIGURATION
.IP \[bu] 2
Enable ZSH Tab Completion
.RS 2
.PP
ZSH tab completion requires the \f[C]compinit\f[] module to be loaded.
Please add the following line to your ~/.zshrc:
.IP
.nf
\f[C]
autoload\ -U\ compinit;\ compinit
\f[]
.fi
.RE
.IP \[bu] 2
Always Ignore Case
.RS 2
.PP
Default behavior is to prioritize exact matches over all else.
For example, \f[C]j\ foo\f[] will prefer /foobar over /FooBar even if
the latter has a higher weight.
To change this behavior and ignore case, add the following environmental
variable in your ~/.bashrc:
.IP
.nf
\f[C]
export\ AUTOJUMP_IGNORE_CASE=1
\f[]
.fi
.RE
.IP \[bu] 2
Prevent Database Entries\[aq] Decay
.RS 2
.PP
Default behavior is to decay unused database entries slowly over time.
Eventually when database limits are hit and maintenance is run, autojump
will purge older less used entries.
To prevent decay, add the following variable in your ~/.bashrc:
.IP
.nf
\f[C]
export\ AUTOJUMP_KEEP_ALL_ENTRIES=1
\f[]
.fi
.RE
.IP \[bu] 2
Prefer Symbolic Links
.RS 2
.PP
Default behavior is to evaluate symbolic links into full paths as to
reduce duplicate entries in the database.
However, some users prefer a shorter working directory path in their
shell prompt.
To switch behavior to prefer symbolic links, add the following
environmental variable in your ~/.bashrc:
.IP
.nf
\f[C]
export\ AUTOJUMP_KEEP_SYMLINKS=1
\f[]
.fi
.RE
.IP \[bu] 2
Autocomplete Additional Commands (Bash only)
.RS 2
.PP
Autojump can be used to autocomplete other commands (e.g.
cp or vim).
To use this feature, add the following environmental variable in your
~/.bashrc:
.IP
.nf
\f[C]
export\ AUTOJUMP_AUTOCOMPLETE_CMDS=\[aq]cp\ vim\[aq]
\f[]
.fi
.PP
Changes require reloading autojump to take into effect.
.RE
.SS ADVANCED USAGE
.IP \[bu] 2
Using Multiple Arguments
.RS 2
.PP
Let\[aq]s assume the following database:
.IP
.nf
\f[C]
30\ \ \ /home/user/mail/inbox\ 10\ \ \ /home/user/work/inbox
\f[]
.fi
.PP
\f[C]j\ in\f[] would jump into /home/user/mail/inbox as the higher
weighted entry.
However you can pass multiple arguments to autojump to prefer a
different entry.
In the above example, \f[C]j\ w\ in\f[] would then jump you into
/home/user/work/inbox.
.RE
.IP \[bu] 2
ZSH Tab Completion
.RS 2
.PP
Tab completion requires two tabs before autojump will display the
completion menu.
However if \f[C]setopt\ nolistambiguous\f[] is enabled, then only one
tab is required.
.RE
.IP \[bu] 2
Change Directory Weight
.RS 2
.PP
To manually change a directory\[aq]s key weight, you can edit the file
\f[I]$XDG_DATA_HOME/autojump/autojump.txt\f[].
Each entry has two columns.
The first is the key weight and the second is the path:
.IP
.nf
\f[C]
29.3383211216\ \ \ /home/user/downloads
\f[]
.fi
.PP
All negative key weights are purged automatically.
.RE
.SS KNOWN ISSUES
.IP \[bu] 2
For bash users, autojump keeps track of directories as a pre-command
hook by modifying $PROMPT_COMMAND.
If you overwrite $PROMPT_COMMAND in ~/.bashrc you can cause problems.
Don\[aq]t do this:
.RS 2
.IP
.nf
\f[C]
export\ PROMPT_COMMAND="history\ -a"
\f[]
.fi
.PP
Do this:
.IP
.nf
\f[C]
export\ PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND\ ;}\ history\ -a"
\f[]
.fi
.RE
.IP \[bu] 2
The jump function \f[C]j\f[] does not support directories that begin
with \f[C]-\f[].
If you want to jump a directory called \f[C]--music\f[], try using
\f[C]j\ music\f[] instead of \f[C]j\ \ \ --music\f[].
.IP \[bu] 2
jumpapplet (bug #59)
.RS 2
.PP
Does not work in Gnome 3 shell or LDXE.
.RE
.SS FILES
.PP
If installed locally, autojump is self-contained in
\f[I]~/.autojump/\f[].
.PP
The database is stored in \f[I]$XDG_DATA_HOME/autojump/autojump.txt\f[].
.SS REPORTING BUGS
.PP
For any usage related issues or feature requests please visit:
.PP
\f[I]https://github.com/joelthelion/autojump/issues\f[]
.SS MAILING LIST
.PP
For release announcements and development related discussion please
visit:
.PP
\f[I]https://groups.google.com/forum/?fromgroups#!forum/autojump\f[]
.SS THANKS
.PP
Special thanks goes out to: Pierre Gueth, Simon Marache-Francisco,
Daniel Jackoway, and many others.
.SS AUTHORS
.PP
autojump was originally written by Joël Schaerer, and currently
maintained by William Ting.
.SS COPYRIGHT
.PP
Copyright © 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
